/**
 * Shared payload shapes for Supabase Realtime broadcast events.
 *
 * Why this file exists: the broadcast publisher (server-flow.ts) and the
 * subscribers (match view, lobby view) used to declare these inline as
 * anonymous types. They drifted — the server sent `publicState` while
 * the client expected `stateAfterG`, and the only way we noticed was a
 * board that visibly never updated.
 *
 * By centralizing the types here:
 *   - Server `broadcastGame(match.id, MovePlayed, payload: MovePlayedPayload)`
 *     gets compile-time enforcement that every field is set.
 *   - Client `ch.on("broadcast", { event: MovePlayed }, (e) => {
 *       const p = e.payload as MovePlayedPayload; ... })` reads from the
 *     same shape — a rename breaks the build, not production.
 *
 * Keep payloads JSON-serializable (no Date, BigInt, Map). Anything not
 * representable in JSON should be stringified on the wire.
 */
import type { ResultReason } from "@/lib/game/lifecycle";
import type {
  AgentMood,
  ExpectedReply,
  GamePhase,
  MoveCandidate,
  MoveEvaluation,
} from "@/lib/db/schema";

/** Fired after a successful applyMove. Drives the live board + clock + move-log. */
export interface MovePlayedPayload {
  matchId: string;
  /** 0-based move index. Subscribers dedupe on this. */
  moveNumber: number;
  /** The move payload the player submitted (game-specific shape). */
  payload: unknown;
  /** Optional LLM-supplied chain-of-thought. Spectator-readable. */
  reasoning: string | null;
  /** Optional self-reported expected value [-1, 1]. */
  evScore: number | null;
  /** Server-recorded wall time the player spent on the move. */
  thinkingMs: number;
  /** x402 payment id for paid-mode per-move fees, else null. */
  x402PaymentId: string | null;
  /** boardgame.io G after the move. Filtered through serializeForSpectator. */
  stateAfterG: unknown;
  /** Agent whose turn it is NOW. May be null in odd cases (e.g. game over). */
  currentTurnAgentId: string | null;
  /** Player id whose turn it is NOW. */
  currentTurnPlayerId: "0" | "1";
  /** ISO timestamp when the now-current player's clock started. */
  turnStartedAt: string;
  /** Per-move budget for player "0". Reset every accepted move under the per-move clock. */
  p1MsLeft: number;
  /** Per-move budget for player "1". Reset every accepted move under the per-move clock. */
  p2MsLeft: number;
  /** True when this broadcast was generated by an autonomous system bot move
   *  (system-mode match), not by an external agent. UI uses this to skip
   *  thinking-time and reasoning rendering. */
  isBot?: boolean;
  /**
   * True when this is the FINAL move of the match — the next thing the
   * client will receive is GameEnded. Set by the agent-move and
   * system-bot-move paths in flow/match.ts when engine.gameOver(...)
   * returned truthy.
   *
   * Clients use this to skip the clock + turn-state updates: there's
   * no "who's next" anymore. Without this flag the client would start
   * the loser's clock for the brief window between this broadcast and
   * GameEnded landing, then catch back up — visibly twitchy.
   */
  isTerminal?: boolean;
  // ---- Phase A: structured reasoning + voice + emotion ----------------------
  // All optional. Subscribers that don't know about these keys ignore them;
  // the spectator UI renders them when present.
  candidates?: MoveCandidate[] | null;
  evaluation?: MoveEvaluation | null;
  plan?: string | null;
  expectedReply?: ExpectedReply | null;
  phase?: GamePhase | null;
  mood?: AgentMood | null;
  emotionTrigger?: string | null;
}

/**
 * Fired when an already-played move's reasoning is filled in or
 * updated via `coliseum_match_annotate`. Spectator UI patches the
 * existing chat bubble keyed by `moveNumber`. Same structured fields
 * as MovePlayedPayload (everything except the move itself, which
 * doesn't change).
 */
export interface MoveAnnotatedPayload {
  matchId: string;
  /** Move index whose reasoning was updated. Subscribers patch in place. */
  moveNumber: number;
  reasoning: string | null;
  candidates?: MoveCandidate[] | null;
  evaluation?: MoveEvaluation | null;
  plan?: string | null;
  expectedReply?: ExpectedReply | null;
  phase?: GamePhase | null;
  mood?: AgentMood | null;
  emotionTrigger?: string | null;
}

/** Fired exactly once on finalizeMatch. Includes ELO and the winner (or null on draw). */
export interface GameEndedPayload {
  matchId: string;
  /** The agent that won. Null only on draws (resultReason === "draw"). */
  winnerAgentId: string | null;
  resultReason: ResultReason;
  /** ELO delta for player "0" (positive = gained, negative = lost). */
  p1EloDelta: number;
  /** ELO delta for player "1". */
  p2EloDelta: number;
}

/** Spectator chat message. Public-channel broadcast on every chat insert. */
export interface ChatMessagePayload {
  id: string;
  speakerOwnerId: string | null;
  anonymousToken: string | null;
  body: string;
  createdAt: string;
}

/** Aggregated emoji reaction. Bumped count, not per-click event. */
export interface ReactionPayload {
  emoji: string;
}

/** Lobby-channel broadcast when a new challenge is posted or a match is created. */
export interface LobbyGameCreatedPayload {
  id: string;
  gameType: string;
  mode: "free" | "paid" | "system";
}

/** Lobby-channel broadcast when a match ends. Drives the "Live now" rail. */
export interface LobbyGameEndedPayload {
  id: string;
}

/**
 * Lobby-channel broadcast when a challenge is accepted and a match is
 * created. Lets lobby subscribers retire the challenge row from the
 * open-challenges list without polling and — once match_list gains
 * wait:true long-poll — wakes any agent sitting in that call.
 */
export interface LobbyGameJoinedPayload {
  /** The new match id. */
  id: string;
  /** The challenge that was consumed. */
  challengeId: string;
  gameType: string;
  mode: "free" | "paid";
}

// ── Autonomous-play per-agent channel payloads ──────────────────────
// Sent on `agent:<agentId>` to wake match_list(wait:true) callers.

/** A match just became active for this agent (challenge accepted or
 *  system-mode match created). The agent should call match_state next. */
export interface MatchActivatedPayload {
  matchId: string;
  gameType: string;
  mode: "free" | "paid" | "system";
}

/** The proposer's challenge was accepted — a new match was created.
 *  Sent to both the proposer AND the acceptor so both sides wake. */
export interface ChallengeAcceptedPayload {
  challengeId: string;
  matchId: string;
  gameType: string;
  mode: "free" | "paid";
}

/** A challenge the agent posted expired without a taker. */
export interface ChallengeExpiredPayload {
  challengeId: string;
  gameType: string;
}

/** Operator or owner recalled this agent — in-flight long-polls should exit. */
export interface AgentRecalledPayload {
  reason: string | null;
  recalledBy: string | null;
}
