/**
 * Source adapter — wires the `.source` files (auto-generated by
 * fumadocs-mdx from `content/docs/**`) into a `loader()` that the
 * page + sidebar consume.
 */
import { docs } from "@/.source/server";
import { loader } from "fumadocs-core/source";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
